### ISSUE TITLE
Post-processor failed: Unknown libvirt domain type: tcg

### ISSUE THREAD

**Issue by qmacpit** [jakobadam/packer-qemu-templates#14]
Hi,

I'm trying to build ubuntu 16.04 vagrant image forvagrant libvirt.
The only change I made was adding: 
_ubuntu1604.json:_
```js
"version" : "1",
"headless": "true"
```
as I'm building on a server. The build fails with the following reason:
```
==> qemu: Gracefully halting virtual machine...
==> qemu: Converting hard drive...
==> qemu: Running post-processor: vagrant
==> qemu (vagrant): Creating Vagrant box for 'libvirt' provider
    qemu (vagrant): Copying from artifact: output-ubuntu1604/ubuntu1604
Build 'qemu' errored: 1 error(s) occurred:

* Post-processor failed: Unknown libvirt domain type: tcg
```

Any help will be much appreciated:)

Cheers,
qmacpit

**Comment by jakobadam** [comment]
Hi

Sorry. I'm not familiar with the internals of the `vagrant libvirt` postprocessor. But very strange that the copying step should throw that error from libvirt. 

Try to get some more debug output with `PACKER_LOG=1`.

Workaround qcow2 -> box
Create the vagrant box with the following tool
https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/tools/create_box.sh

kind regards,
Jakob

**Comment by qmacpit** [comment]
Thanks!

The logs I have provided are with ```PACKER_LOG=1``` already.
I'll check the workaround out :)

**Comment by jakobadam** [comment]
Maybe the libvirt log tells more?
