### ISSUE TITLE
Why is vagrant stuff in the ubuntu.json file?

### ISSUE THREAD

**Issue by mcpherson** [jakobadam/packer-qemu-templates#16]
Hoping I can just ask a quick question while I debug my problem.

I notice that lots of vagrant-related things are in the `ubuntu.json` file. For example, that file appears to execute `scripts\vagrant.sh` (which may or may not be causing my problem). Why would that be in `ubuntu.json` as opposed (or in addition) to `ubuntu-vagrant.json`? Maybe I'm missing some variables or keywords that control a vagrant/non-vagrant execition path through that file?

**Comment by jakobadam** [comment]
The only difference in the files are the `post-processor` step that boxes
the qcow2. Fine with me if you rip out the vagrant stuff.

-- Jakob

2016-11-24 0:44 GMT+01:00 Allen McPherson <notifications@github.com>:
