### ISSUE TITLE
*WinRM* not available on *Windows 10 Enterprise*

### ISSUE THREAD

**Issue by skvl** [jakobadam/packer-qemu-templates#19]
I have cloned your project and tried to run `packer build windows-10-enterprise.json`. After successful installation packer still wait for *WinRM* to become available.

**Comment by jakobadam** [comment]
A bug introduced in a recent version of Packer – ah the joys of software. Don't know what the bug is, maybe related to:

https://github.com/mitchellh/packer/blob/master/CHANGELOG.md

> (Unreleased)
> BUG FIXES:
> builder/qemu: Explicitly set WinRMPort for StepConnect. [GH-4321]
> 

Not my priority to investigate.

I'm having success with:
https://releases.hashicorp.com/packer/0.10.1/

**Comment by skvl** [comment]
@jakobadam thank you for reply. I have dealt with this recently.

You are right. See [PR](https://github.com/mitchellh/packer/pull/4321). This would appear in 0.12.2. I have got it with command:
```
     go get -u github.com/mitchellh/packer
```

**Comment by jakobadam** [comment]
Thanks for the pointer.
