### ISSUE TITLE
windows 10 stuck at waiting for winrm

### ISSUE THREAD

**Issue by xahare** [jakobadam/packer-qemu-templates#21]
fedora 25, packer 0.12.1

packer build windows-10-enterprise-vagrant.json

seems fine until it hits this,
Typing the boot command over VNC...
Waiting for WinRM to become available...

and then its just stuck there.

**Comment by jakobadam** [comment]
https://github.com/jakobadam/packer-qemu-templates/issues/19

**Comment by jakobadam** [comment]
Checkout that issue. 

-- Jakob

**Comment by xahare** [comment]
yea, bug in packer. git version fixes it.
